sudo: false
language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '8'
before_script:
  - yarn global add codecov
script:
  - yarn test
  - yarn lint
  - yarn flow
  - yarn build:flow
after_success:
  - codecov
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - yarn global add travis-deploy-once
  - travis-deploy-once 'yarn semantic-release'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
