sudo: false
language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '6'
before_script:
  - yarn global add codecov
  - yarn global add semantic-release
script:
  - npm test
  - npm run lint
  - npm run flow
  - npm run build:flow
  - npm run build:typescript
  - npm run typescript
after_success:
  - codecov
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - semantic-release pre && npm publish && semantic-release post
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
