language: node_js
node_js:
  - '12'
before_script:
  - yarn global add codecov
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install: yarn --frozen-lockfile
script:
  - yarn test
  - yarn lint
  - yarn flow
  - yarn build:flow
  - yarn build:typescript
  - yarn typescript
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - yarn global add travis-deploy-once
  - travis-deploy-once 'yarn semantic-release'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
