name: Node CI

on: [push, pull_request]

jobs:
  report-coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Report Code Coverage
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        fail_ci_if_error: true
