name: Node CI

on: [push, pull_request] # Run on Push and Pull Requests

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x] # Only run the 10.x build

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Core Dependencies 
      run: |
        npm install -g yarn
        yarn global add codecov
        yarn --frozen-lockfile
    - name: Jest Tests
      run: yarn test
    - name: Linting
      run: yarn lint
    - name: Build and Check Flow Types
      run: yarn flow
    - name: Build and Check TS Types
      run: | 
        yarn build:flow
        yarn build:typescript
        yarn typescript
